namespace RepWizard.Core.Entities;

/// <summary>
/// A multi-week structured training program, optionally generated by the AI Coach.
/// </summary>
public class TrainingProgram : BaseEntity
{
    public Guid UserId { get; set; }
    public string Name { get; set; } = string.Empty;
    public int DurationWeeks { get; set; }
    public string GoalDescription { get; set; } = string.Empty;
    public bool GeneratedByAi { get; set; } = false;
    public string? AiReasoning { get; set; }
    public bool IsActive { get; set; } = false;
    public DateTime? ActivatedAt { get; set; }

    // Navigation properties
    public User? User { get; set; }
    public ICollection<ProgramWeek> Weeks { get; set; } = new List<ProgramWeek>();

    /// <summary>
    /// Returns the total number of scheduled training days across all weeks.
    /// </summary>
    public int GetTotalTrainingDays()
        => Weeks.SelectMany(w => w.Days).Count(d => !d.RestDay);

    /// <summary>
    /// Returns the current week based on activation date.
    /// Returns null if the program is not active.
    /// </summary>
    public ProgramWeek? GetCurrentWeek()
    {
        if (!IsActive || !ActivatedAt.HasValue) return null;

        var daysSinceStart = (DateTime.UtcNow - ActivatedAt.Value).TotalDays;
        var weekNumber = (int)Math.Floor(daysSinceStart / 7) + 1;
        return Weeks.FirstOrDefault(w => w.WeekNumber == weekNumber);
    }

    /// <summary>
    /// Activates the program. Throws if already active.
    /// </summary>
    public void Activate()
    {
        if (IsActive)
            throw new InvalidOperationException("Program is already active.");

        IsActive = true;
        ActivatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Deactivates the program.
    /// </summary>
    public void Deactivate()
    {
        IsActive = false;
    }

    /// <summary>
    /// Validates that the program contains at least one deload week if duration >= 4 weeks.
    /// Per the science-based constraint: programs of 4+ weeks must include at least one deload week.
    /// </summary>
    public bool HasRequiredDeloadWeek()
    {
        if (DurationWeeks < 4) return true;
        return Weeks.Any(w => w.DeloadWeek);
    }
}
